{
 "title": "Minecraft",
 "tags": [
  "homelab",
  "minecraft"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"minecraft\"}"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minecraft_player_online" }
   ]
  },
  {
   "title": "Minecraft server logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"games\", job=\"minecraft\", service=\"minecraft\", log_type=\"server\"}"
    }
   ]
  }
 ]
}