services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    restart: unless-stopped
    stop_grace_period: 2m
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      VERSION: "1.20.1"
      CF_SERVER_MOD: "https://mediafilez.forgecdn.net/files/8619/337/Craft%20to%20Exile%202%20SERVER-2.0.4.zip"
      MEMORY: 8G
      MOTD: |-
        §d§lEVENT §f✦ §eDouble Backshots XP
        §7Lasts for all of §aSeptember§7!
      ICON: /data/server-icon.png
      OVERRIDE_ICON: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: America/Winnipeg
      DIFFICULTY: normal
      LEVEL: Backshots Central
      OPS: |-
        ratcho19
      SERVER_NAME: Backshots Central
      LOG_TIMESTAMP: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD:?set RCON_PASSWORD}"
      MANAGEMENT_SERVER_ENABLED: "true"
      MANAGEMENT_SERVER_HOST: localhost
      MANAGEMENT_SERVER_PORT: "6767"
      MANAGEMENT_SERVER_ALLOWED_ORIGINS: localhost
      MANAGEMENT_SERVER_SECRET: "${MANAGEMENT_SERVER_SECRET:?set MANAGEMENT_SERVER_SECRET}"
    volumes:
      - /srv/compose/minecraft/data:/data

  minecraft-exporter:
    image: itzg/mc-monitor:0.15.0
    container_name: minecraft-exporter
    restart: unless-stopped
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft:25565
    ports:
      - "10.200.1.20:8080:8080"
    depends_on:
      - minecraft
