services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8180:80"        # HTTP
      - "8181:81"        # Web UI
      - "41443:443"      # HTTPS
    volumes:
      - /var/lib/docker/volumes/nginx:/data
      - /var/lib/docker/volumes/nginx/letsencrypt:/etc/letsencrypt
      - /var/lib/docker/volumes/nginx/logs:/var/logs/nginx
